# Generated by Django 5.1.7 on 2026-09-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ticket_number',
            field=models.CharField(
                blank=True,
                default='',
                max_length=30
            ),
        ),
    ]
