# Generated by Django 5.1.7 on 2026-09-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticapp', '0003_alter_team_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], max_length=20)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('booking_reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
