# Generated by Django 5.1.7 on 2026-09-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticapp', '0004_ticketbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Used', 'Used'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
