# Generated by Django 5.1.7 on 2026-09-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticapp', '0005_ticketbooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooking',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
