# Generated by Django 5.1.7 on 2026-09-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticapp', '0006_ticketbooking_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
