# Generated by Django 5.1.7 on 2026-09-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moticapp', '0008_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
