# Generated by Django 5.1.7 on 2026-09-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moticapp', '0010_alter_team_id_alter_ticketbooking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.DeleteModel(
            name='TicketBooking',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
